name: All Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.71.1

      - name: Add wasm32-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown

      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -y

      - name: Holochain Setup
        uses: supplypike/setup-bin@v3
        with:
          name: holochain
          version: "0.2.2"
          uri: https://github.com/spartan-holochain-counsel/holochain-nix-shell-configs/releases/download/holochain-0.2.2/holochain-0.2.2

      - name: Lair Keystore Setup
        uses: supplypike/setup-bin@v3
        with:
          name: lair-keystore
          version: "0.3.0"
          uri: https://github.com/spartan-holochain-counsel/holochain-nix-shell-configs/releases/download/holochain-0.2.2/lair-keystore-0.3.0

      - name: Holochain CLI Setup
        uses: supplypike/setup-bin@v3
        with:
          name: hc
          version: "0.2.2"
          uri: https://github.com/spartan-holochain-counsel/holochain-nix-shell-configs/releases/download/holochain-0.2.2/hc-0.2.2

      - name: Create expected nix dir
        run: sudo mkdir -p /nix/store/ld03l52xq2ssn4x0g5asypsxqls40497-glibc-2.37-8/lib/

      - name: Create link to expected nix dependency
        run: sudo ln -s /lib64/ld-linux-x86-64.so.2 /nix/store/ld03l52xq2ssn4x0g5asypsxqls40497-glibc-2.37-8/lib/ld-linux-x86-64.so.2

      - name: Run Tests
        run: make test-debug
