name: All Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.71.1

      - name: Add wasm32-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown

      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -y

      - name: Holochain Setup
        uses: supplypike/setup-bin@v3
        with:
          name: holochain
          version: "0.2.2"
          uri: https://github.com/spartan-holochain-counsel/holochain-nix-shell-configs/releases/download/holochain-0.2.2/holochain-0.2.2

      - name: Lair Keystore Setup
        uses: supplypike/setup-bin@v3
        with:
          name: lair-keystore
          version: "0.3.0"
          uri: https://github.com/spartan-holochain-counsel/holochain-nix-shell-configs/releases/download/holochain-0.2.2/lair-keystore-0.3.0

      - name: Holochain CLI Setup
        uses: supplypike/setup-bin@v3
        with:
          name: hc
          version: "0.2.2"
          uri: https://github.com/spartan-holochain-counsel/holochain-nix-shell-configs/releases/download/holochain-0.2.2/hc-0.2.2

      - name: Print PATH Variable
        run: echo $PATH

      - name: Print LD_LIBRARY_PATH
        run: echo $LD_LIBRARY_PATH

      - name: List LD_LIBRARY_PATH
        run: ls -la $LD_LIBRARY_PATH

      - name: List /lib64
        run: ls -la /lib64

      - name: Check binaries permissions
        run: ls -l /opt/hostedtoolcache/hc/0.2.2/x64/hc

      - name: Check symlinks
        run: ldd /opt/hostedtoolcache/hc/0.2.2/x64/hc

      - name: Create expected nix dir
        run: mkdir -p /nix/store/ld03l52xq2ssn4x0g5asypsxqls40497-glibc-2.37-8/lib/

      - name: Print HC version
        run: hc --version

      - name: Print Holochain version
        run: holochain --version

      - name: Print Lair version
        run: lair-keystore --version

      # - name: Run Tests
      #   run: make test-debug
