name: All Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

env:
  RUST_VERSION: 1.75.0
  RELEASE_TAG: holochain-0.3.0-beta-dev.37
  HOLOCHAIN_VERSION: 0.3.0-beta-dev.37
  LAIR_KEYSTORE_VERSION: 0.4.3
  HC_VERSION: 0.3.0-beta-dev.36
  NIX_STORE_PATH: "/nix/store/cyrrf49i2hm1w7vn2j945ic3rrzgxbqs-glibc-2.38-44/lib/"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: wasm32-unknown-unknown

      - name: Holochain Setup
        uses: supplypike/setup-bin@v3
        with:
          name: holochain
          version: "${{ env.HOLOCHAIN_VERSION }}"
          uri: https://github.com/spartan-holochain-counsel/holochain-nix-shell-configs/releases/download/${{ env.RELEASE_TAG }}/holochain-${{ env.HOLOCHAIN_VERSION }}

      - name: Lair Keystore Setup
        uses: supplypike/setup-bin@v3
        with:
          name: lair-keystore
          version: "${{ env.LAIR_KEYSTORE_VERSION }}"
          uri: https://github.com/spartan-holochain-counsel/holochain-nix-shell-configs/releases/download/${{ env.RELEASE_TAG }}/lair-keystore-${{ env.LAIR_KEYSTORE_VERSION }}

      - name: Holochain CLI Setup
        uses: supplypike/setup-bin@v3
        with:
          name: hc
          version: "${{ env.HC_VERSION }}"
          uri: https://github.com/spartan-holochain-counsel/holochain-nix-shell-configs/releases/download/${{ env.RELEASE_TAG }}/hc-${{ env.HC_VERSION }}

      - name: Create expected symlink in nix path dependency
        run: |
          sudo mkdir -p ${{ env.NIX_STORE_PATH }}
          sudo ln -s /lib64/ld-linux-x86-64.so.2 ${{ env.NIX_STORE_PATH }}

      - name: Check glib version
        run: |
          ldd --version

      - name: Upgrade
        run: |
          sudo apt-get update
          sudo apt-get -y upgrade

      - name: Check glib version
        run: |
          ldd --version

      - name: Upgrade dist
        run: |
          sudo apt-get -y dist-upgrade

      - name: Check glib version
        run: |
          ldd --version

      - name: Test binaries
        run: |
          hc --version
          holochain --version
          lair-keystore --version

      - name: Build Packages
        run: make build

      - name: Run Tests
        run: |
          output=$(make test-debug | tee >(cat >&2))
          passing=$(echo "$output" | grep -oP '\d+ passing' | grep -oP '\d+' || echo 0)
          failing=$(echo "$output" | grep -oP '\d+ failing' | grep -oP '\d+' || echo 0)
          pending=$(echo "$output" | grep -oP '\d+ pending' | grep -oP '\d+' || echo 0)
          echo "## Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Passed   | Failed   | Pending  |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|----------|----------|" >> $GITHUB_STEP_SUMMARY
          echo "| $passing | $failing | $pending |" >> $GITHUB_STEP_SUMMARY
